
#ifndef DCT_CONFIG_HPP_
#define DCT_CONFIG_HPP_

#include "../WAXM_config.h"


#define DCT_HAVE_PUGIXML 	WAXM_HAVE_PUGIXML
#define DCT_HAVE_POSIX 		WAXM_HAVE_POSIX
#define DCT_HAVE_CLOCK_GETTIME 	WAXM_HAVE_CLOCK_GETTIME


#define DCT_CPP_MULTITHREADING	 	WAXM_CPP_MULTITHREADING
#define DCT_OMP_MULTITHREADING		WAXM_OMP_MULTITHREADING

#define DCT_HAVE_CPP_2011 			WAXM_HAVE_CPP_2011

#endif




